version: '3.1'

services:
  generator:
    build:
      context: .
    image: locahost:55000/gen:10
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"